### ISSUE TITLE
关于编译

### ISSUE THREAD

**Issue by FanJZSS** [pomelohan/twrp_device_oppo_OP4EA7#1]
您好，请问这个twrp是可以在reno5p+安卓11上使用吗？可否指点一下如何编译，或者您还有成品留存下来吗？

**Comment by pomelohan** [comment]
很抱歉这么晚才回复，前段时间在忙别的事情忘记回复了。

这个 TWRP Device Tree 的分支就是 android-11，顾名思义就是可以在 Reno 5 Pro+ 的 Android 11 底包上工作的。关于编译的话可以自行 Google/百度甚至 ChatGPT 来获得帮助，我在 issues 中不能提供任何帮助。因为设备很早就卖掉了，所以成品留存是不存在的，需要自行编译或者问哪位网友有留存。

如果没有其他问题请记得及时关闭当前 issue，如果仍然有问题可以继续向我提问 ;-)
